// <auto-generated />
using System;
using ISTP_LABA_3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LR3Proj.Migrations
{
    [DbContext(typeof(BankAppContext))]
    [Migration("20190922135258_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ISTP_LABA_3.Models.Bank", b =>
                {
                    b.Property<int>("BankID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("BankID");

                    b.ToTable("Bank");
                });

            modelBuilder.Entity("ISTP_LABA_3.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientType")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.HasKey("ClientID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("ISTP_LABA_3.Models.Condition", b =>
                {
                    b.Property<int>("ConditionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Mark")
                        .IsRequired();

                    b.Property<int>("MaxSum");

                    b.Property<int>("MinSum");

                    b.Property<string>("Special");

                    b.HasKey("ConditionID");

                    b.ToTable("Condition");
                });

            modelBuilder.Entity("ISTP_LABA_3.Models.Contract", b =>
                {
                    b.Property<int>("ContractID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientID");

                    b.Property<DateTime>("FinishDate");

                    b.Property<int>("OfferID");

                    b.Property<DateTime>("SigningDate");

                    b.Property<float>("Sum");

                    b.HasKey("ContractID");

                    b.HasIndex("ClientID");

                    b.HasIndex("OfferID");

                    b.ToTable("Contract");
                });

            modelBuilder.Entity("ISTP_LABA_3.Models.Offer", b =>
                {
                    b.Property<int>("OfferID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BankID");

                    b.Property<int>("ConditionID");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("OfferTypeID");

                    b.Property<int>("Percentage");

                    b.HasKey("OfferID");

                    b.HasIndex("BankID");

                    b.HasIndex("ConditionID");

                    b.HasIndex("OfferTypeID");

                    b.ToTable("Offer");
                });

            modelBuilder.Entity("ISTP_LABA_3.Models.OfferType", b =>
                {
                    b.Property<int>("OfferTypeID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("OfferTypeID");

                    b.ToTable("OfferType");
                });

            modelBuilder.Entity("ISTP_LABA_3.Models.Contract", b =>
                {
                    b.HasOne("ISTP_LABA_3.Models.Client", "Client")
                        .WithMany("Contracts")
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ISTP_LABA_3.Models.Offer", "Offer")
                        .WithMany("Contracts")
                        .HasForeignKey("OfferID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ISTP_LABA_3.Models.Offer", b =>
                {
                    b.HasOne("ISTP_LABA_3.Models.Bank", "Bank")
                        .WithMany("Offers")
                        .HasForeignKey("BankID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ISTP_LABA_3.Models.Condition", "Condition")
                        .WithMany()
                        .HasForeignKey("ConditionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ISTP_LABA_3.Models.OfferType", "OfferType")
                        .WithMany("Offers")
                        .HasForeignKey("OfferTypeID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
